/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carwashbookingsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sfiso
 */
public class frmCustomerHome extends javax.swing.JFrame {

    /**
     * Creates new form frmCustomerHome
     */
    public frmCustomerHome() {
        initComponents();
    }
public String strloggedInEmail;

public void mViewBookings()
    {
        LocalDate todayDate = LocalDate.now();
        String strDBConnectionString = "jdbc:mysql://localhost:3306/carwash_db";
        String strDBUser = "root";
        String strDBPassword = "password";
        
        Connection conMySQLConnectionString = null;
        Statement stStatement = null;
        ResultSet rsBookings = null;
        
        DefaultTableModel model = (DefaultTableModel)tblBookings.getModel();
              
        try
        {
            conMySQLConnectionString = DriverManager.getConnection(strDBConnectionString, strDBUser, strDBPassword);
            
            stStatement = conMySQLConnectionString.createStatement();
            
            String strSQLQuery = "SELECT * FROM tblBookings where email = '"+ strloggedInEmail +"' AND date > '" + todayDate + "'";
            
            rsBookings = stStatement.executeQuery(strSQLQuery);
            
            ResultSetMetaData rmst = rsBookings.getMetaData();
            
            int intColumnCount = rmst.getColumnCount();

            Vector vRow;
            
            while(rsBookings.next())
            {
                vRow = new Vector(intColumnCount);
                for(int i = 1; i <= intColumnCount; i++)
                {
                    vRow.add(rsBookings.getString(i));   
                }
                
                model.addRow(vRow);
            }
             //Gets the beneficiaries data
            
            if(model.getRowCount() == 0) // checks if the searched record was found
            {
                JOptionPane.showMessageDialog(rootPane, "No data is currently saved on the database");  
            }    
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error" + e);
        }
        finally
        {
            try
            {
                stStatement.close();
                rsBookings.close();
                conMySQLConnectionString.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
    }

private void mCancelBooking()    //Cancels booking but Deleting data from the database
    {
        String strDBConnectionString = "jdbc:mysql://localhost:3306/carwash_db";
        String strDBUser = "root";
        String strDBPassword = "password";

        try
        {
            Connection conMySQLConnectionString = DriverManager.getConnection(strDBConnectionString, strDBUser, strDBPassword);
            Statement myStatement = conMySQLConnectionString.createStatement();
            
            try
            {
                String strBookingID = tblBookings.getValueAt(tblBookings.getSelectedRow(), 0).toString().toUpperCase();

                String  strQuery = "DELETE FROM tblBookings "
                                 + "WHERE ID = " + "'" + strBookingID + "'" ;  
                
                myStatement.execute(strQuery);
                myStatement.close();
                
                DefaultTableModel model = (DefaultTableModel)tblBookings.getModel();
                model.removeRow(tblBookings.getSelectedRow());
                
                JOptionPane.showMessageDialog(rootPane, "Booking has been cancelled.");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, e);
            }    
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBookings = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        pnlViewPastBookings = new javax.swing.JPanel();
        lblViewPastBookingsIcon = new javax.swing.JLabel();
        lblViewPastBookings = new javax.swing.JLabel();
        pnlCancelBookings = new javax.swing.JPanel();
        lblCancelBookingIcon = new javax.swing.JLabel();
        lblCancelBooking = new javax.swing.JLabel();
        pnlMakeABooking = new javax.swing.JPanel();
        lblMakeABookingIcon = new javax.swing.JLabel();
        lblMakeABooking = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Bookings");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));

        btnLogout.setBackground(new java.awt.Color(102, 153, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnLogout.setOpaque(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        tblBookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Car Registration", "Vehicle Type", "Wash Type", "Date", "Time", "Booking outcome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBookings.setRowHeight(25);
        tblBookings.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblBookings);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setOpaque(false);

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Control Panel");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        pnlViewPastBookings.setOpaque(false);
        pnlViewPastBookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlViewPastBookingsMousePressed(evt);
            }
        });

        lblViewPastBookingsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewPastBookingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/g3937.png"))); // NOI18N
        lblViewPastBookingsIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewPastBookingsIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewPastBookingsIconMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblViewPastBookingsIconMousePressed(evt);
            }
        });

        lblViewPastBookings.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblViewPastBookings.setForeground(new java.awt.Color(255, 255, 255));
        lblViewPastBookings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewPastBookings.setText("View Past Bookings");
        lblViewPastBookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewPastBookingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewPastBookingsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblViewPastBookingsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlViewPastBookingsLayout = new javax.swing.GroupLayout(pnlViewPastBookings);
        pnlViewPastBookings.setLayout(pnlViewPastBookingsLayout);
        pnlViewPastBookingsLayout.setHorizontalGroup(
            pnlViewPastBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblViewPastBookingsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblViewPastBookings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlViewPastBookingsLayout.setVerticalGroup(
            pnlViewPastBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewPastBookingsLayout.createSequentialGroup()
                .addComponent(lblViewPastBookingsIcon)
                .addGap(2, 2, 2)
                .addComponent(lblViewPastBookings)
                .addGap(43, 43, 43))
        );

        jPanel7.add(pnlViewPastBookings);

        pnlCancelBookings.setOpaque(false);
        pnlCancelBookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlCancelBookingsMousePressed(evt);
            }
        });

        lblCancelBookingIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelBookingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/polygon25629.png"))); // NOI18N
        lblCancelBookingIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelBookingIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelBookingIconMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCancelBookingIconMousePressed(evt);
            }
        });

        lblCancelBooking.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblCancelBooking.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelBooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelBooking.setText("Cancel Booking");
        lblCancelBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancelBookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancelBookingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCancelBookingMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlCancelBookingsLayout = new javax.swing.GroupLayout(pnlCancelBookings);
        pnlCancelBookings.setLayout(pnlCancelBookingsLayout);
        pnlCancelBookingsLayout.setHorizontalGroup(
            pnlCancelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCancelBookingIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblCancelBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCancelBookingsLayout.setVerticalGroup(
            pnlCancelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCancelBookingsLayout.createSequentialGroup()
                .addComponent(lblCancelBookingIcon)
                .addGap(2, 2, 2)
                .addComponent(lblCancelBooking)
                .addGap(43, 43, 43))
        );

        jPanel7.add(pnlCancelBookings);

        pnlMakeABooking.setOpaque(false);
        pnlMakeABooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlMakeABookingMousePressed(evt);
            }
        });

        lblMakeABookingIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMakeABookingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/g24.png"))); // NOI18N
        lblMakeABookingIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMakeABookingIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMakeABookingIconMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMakeABookingIconMousePressed(evt);
            }
        });

        lblMakeABooking.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblMakeABooking.setForeground(new java.awt.Color(255, 255, 255));
        lblMakeABooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMakeABooking.setText("Make A Booking");
        lblMakeABooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMakeABookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMakeABookingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMakeABookingMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlMakeABookingLayout = new javax.swing.GroupLayout(pnlMakeABooking);
        pnlMakeABooking.setLayout(pnlMakeABookingLayout);
        pnlMakeABookingLayout.setHorizontalGroup(
            pnlMakeABookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMakeABookingIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(lblMakeABooking, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        pnlMakeABookingLayout.setVerticalGroup(
            pnlMakeABookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMakeABookingLayout.createSequentialGroup()
                .addComponent(lblMakeABookingIcon)
                .addGap(2, 2, 2)
                .addComponent(lblMakeABooking)
                .addContainerGap())
        );

        jPanel7.add(pnlMakeABooking);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel12.add(jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout)))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        frmLogin frmL = new frmLogin();
        frmL.show();
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void lblViewPastBookingsIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPastBookingsIconMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblViewPastBookingsIconMouseEntered

    private void lblViewPastBookingsIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPastBookingsIconMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblViewPastBookingsIconMouseExited

    private void lblViewPastBookingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPastBookingsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblViewPastBookingsMouseEntered

    private void lblViewPastBookingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPastBookingsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblViewPastBookingsMouseExited

    private void lblMakeABookingIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMakeABookingIconMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMakeABookingIconMouseEntered

    private void lblMakeABookingIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMakeABookingIconMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMakeABookingIconMouseExited

    private void lblMakeABookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMakeABookingMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMakeABookingMouseEntered

    private void lblMakeABookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMakeABookingMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMakeABookingMouseExited

    private void lblCancelBookingIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelBookingIconMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCancelBookingIconMouseEntered

    private void lblCancelBookingIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelBookingIconMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCancelBookingIconMouseExited

    private void lblCancelBookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelBookingMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCancelBookingMouseEntered

    private void lblCancelBookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelBookingMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCancelBookingMouseExited

    private void pnlMakeABookingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMakeABookingMousePressed
 frmMakeBooking frmMB = new frmMakeBooking();
                frmMB.strloggedInEmail = strloggedInEmail;;
                frmMB.show();
                this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_pnlMakeABookingMousePressed

    private void pnlViewPastBookingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlViewPastBookingsMousePressed
     frmPastBookings frmPB = new frmPastBookings();
                frmPB.strloggedInEmail = strloggedInEmail;;
                frmPB.show();
                this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_pnlViewPastBookingsMousePressed

    private void lblViewPastBookingsIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPastBookingsIconMousePressed
     frmPastBookings frmPB = new frmPastBookings();
                frmPB.strloggedInEmail = strloggedInEmail;;
                frmPB.show();
                this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_lblViewPastBookingsIconMousePressed

    private void lblViewPastBookingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPastBookingsMousePressed
    frmPastBookings frmPB = new frmPastBookings();
                frmPB.strloggedInEmail = strloggedInEmail;;
                frmPB.show();
                this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_lblViewPastBookingsMousePressed

    private void lblMakeABookingIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMakeABookingIconMousePressed
 frmMakeBooking frmMB = new frmMakeBooking();
                frmMB.strloggedInEmail = strloggedInEmail;;
                frmMB.show();
                this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lblMakeABookingIconMousePressed

    private void lblMakeABookingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMakeABookingMousePressed
 frmMakeBooking frmMB = new frmMakeBooking();
                frmMB.strloggedInEmail = strloggedInEmail;;
                frmMB.show();
                this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lblMakeABookingMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
mViewBookings();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void lblCancelBookingIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelBookingIconMousePressed
if(tblBookings.getSelectedRowCount() != 1)
        {
            JOptionPane.showMessageDialog(null, "Please select a row to perform this action");
        }
        else
        {
            mCancelBooking();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_lblCancelBookingIconMousePressed

    private void lblCancelBookingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelBookingMousePressed
     if(tblBookings.getSelectedRowCount() != 1)
        {
            JOptionPane.showMessageDialog(null, "Please select a row to perform this action");
        }
        else
        {
            mCancelBooking();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_lblCancelBookingMousePressed

    private void pnlCancelBookingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCancelBookingsMousePressed
    if(tblBookings.getSelectedRowCount() != 1)
        {
            JOptionPane.showMessageDialog(null, "Please select a row to perform this action");
        }
        else
        {
            mCancelBooking();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_pnlCancelBookingsMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCustomerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCancelBooking;
    private javax.swing.JLabel lblCancelBookingIcon;
    private javax.swing.JLabel lblMakeABooking;
    private javax.swing.JLabel lblMakeABookingIcon;
    private javax.swing.JLabel lblViewPastBookings;
    private javax.swing.JLabel lblViewPastBookingsIcon;
    private javax.swing.JPanel pnlCancelBookings;
    private javax.swing.JPanel pnlMakeABooking;
    private javax.swing.JPanel pnlViewPastBookings;
    private javax.swing.JTable tblBookings;
    // End of variables declaration//GEN-END:variables
}
